#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <cstdlib>
#include <iostream>
#include <unistd.h>
#include <vector>
#include <poll.h>
#include <errno.h>
#include <cassert>
#include <fcntl.h>
#include <cstring>

#include "./command_parser.h"

const int MAX_ALLOWED_MSG_SIZE = 65536;

struct Conn {
    int fd = -1;
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    std::vector<char> incoming;  // data to be parsed by the application
    std::vector<char> outgoing;  // responses generated by the application
};

void fd_set_nb(int fd){ // set fd as non blocking
    errno = 0;
    int flags = fcntl(fd, F_GETFL, 0);
    if (errno) {
        perror("fcntl error");
        abort();
    }

    flags |= O_NONBLOCK;

    errno = 0;
    (void)fcntl(fd, F_SETFL, flags);
    if (errno) {
        perror("fcntl error");
        abort();
    }
}

void append(std::vector<char> &v, char* buff, size_t n){
    v.insert(v.end(), buff, buff + n);
}

void erase_from_start(std::vector<char> &v, size_t n){
    v.erase(v.begin(), v.begin() + n);
}

Conn* handle_new_connection(int sockfd){
    struct sockaddr_in clientaddr{};
    socklen_t clientlen = sizeof(clientaddr);
    int client_fd = accept(sockfd, (struct sockaddr* ) &clientaddr, &clientlen);
    if(client_fd<0){
        perror("accept in failed");
        return NULL;
    }

    char client_ip[INET_ADDRSTRLEN];
    if (inet_ntop(AF_INET, &clientaddr.sin_addr, client_ip, sizeof(client_ip))) {
        std::cout << "New client: " << client_ip << ": " << ntohs(clientaddr.sin_port) << "\n";
    }

    fd_set_nb(client_fd);
    Conn* conn = new Conn();
    conn->fd = client_fd;
    conn->want_read = true;
    return conn;
}

bool try_processing_one(Conn* conn){
    if(conn->incoming.size() < 4){
        return false; // wait for some time
    }
    uint32_t msg_len = 0;
    memcpy(&msg_len, conn->incoming.data(), 4);

    msg_len = ntohl(msg_len);

    if(msg_len>MAX_ALLOWED_MSG_SIZE){
        std::cout << "Message size is too big, dropping connection" << "\n";
        conn->want_close = true;
        return false;
    }

    if(conn->incoming.size() < 4 + msg_len){
        return false; // wait more
    }

    std::vector<char>req(msg_len);
    memcpy(req.data(), conn->incoming.data() + 4, msg_len);

    std::vector<char> res = command_parser(req);

    erase_from_start(conn->incoming, 4+msg_len);

    uint32_t res_len = htonl((uint32_t)(res.size()));
    char res_header[4];
    memcpy(res_header, &res_len, 4);
    
    append(conn->outgoing, res_header, 4);
    append(conn->outgoing, res.data(), (size_t)res.size());
    conn->want_write = true;

    return true;
}

void handle_write(Conn* conn){
    ssize_t n = write(conn->fd, conn->outgoing.data(), (size_t)(conn->outgoing.size()));

    if(n < 0 and (errno == EAGAIN || errno == EWOULDBLOCK)){
        return ;
    }
    if(n < 0){
        conn->want_close = true;
        return;
    }

    erase_from_start(conn->outgoing, n);

    if(conn->outgoing.size() == 0){
        conn->want_read = true;
        conn->want_write = false;
    }
}


void handle_read(Conn* conn){
    char buff[65536];
    ssize_t n = read (conn->fd, buff, sizeof(buff));
    if(n<0 and errno == EAGAIN){
        return ; // nothing to read
    }
    if(n < 0){
        if(errno == EAGAIN || errno == EWOULDBLOCK){
            return;
        }
        if(errno == EINTR){
            return;
        }
        conn->want_close = true;
        return;
    }
    if(n == 0){
        conn->want_close = true;
        return;
    }

    append(conn->incoming, buff, n);

    while(try_processing_one(conn)){};

    if(conn->outgoing.size() > 0){
        conn->want_read = false;
        conn->want_write = true;
        handle_write(conn);
    }
}

int main(int argc, char **argv){

    if(argc!=3){
        std::cerr << "Usage: " << argv[0] << " <IP> <PORT>\n";
        exit(1);
    }

    const char *SERV_IP = argv[1];
    uint16_t SERV_PORT = static_cast<uint16_t>(std::stoi(argv[2]));

    int sockfd;
    if( (sockfd = socket(AF_INET, SOCK_STREAM, 0)) < 0){
        perror("socket creation failed");
        exit(1);
    }

    int val = 1;
    setsockopt(sockfd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

    struct sockaddr_in servaddr{};
    servaddr.sin_family = AF_INET;
    servaddr.sin_port = htons(SERV_PORT);
    inet_pton(AF_INET, SERV_IP , &servaddr.sin_addr);

    if( (bind (sockfd, (struct sockaddr *) &servaddr, sizeof(servaddr))) <0){
        perror("socket bind failed");
        exit(1);
    }


    if( (listen(sockfd, SOMAXCONN)) < 0){
        perror("listen failed");
        exit(1);
    }

    std::vector<Conn *> fd2conn;
    std::vector<struct pollfd> poll_args;

    while(true){
        poll_args.clear();

        struct pollfd pfd = {sockfd, POLLIN, 0};
        poll_args.push_back(pfd);
        for( Conn* conn : fd2conn){
            if(!conn)continue;
            struct pollfd pfd = {conn->fd, POLLERR, 0};
            if(conn->want_read){
                pfd.events |= POLLIN;
            }
            if(conn->want_write){
                pfd.events |= POLLOUT;
            }
            poll_args.push_back(pfd);
        }

        int ready = poll(poll_args.data(), static_cast<nfds_t>(poll_args.size()), -1);
        
        if(ready<0 and errno == EINTR ){
            continue;
        }
        if(ready<0){
            perror("poll");
            abort();
        }

        if(poll_args[0].revents){
            Conn* conn = handle_new_connection(poll_args[0].fd);
            if(fd2conn.size() <= (size_t)conn->fd){
                fd2conn.resize(conn->fd+1);
            }
            fd2conn[conn->fd] = conn;
        }

        for(size_t i = 1; i < poll_args.size(); i++){
            struct pollfd pfd = poll_args[i];
            if(pfd.revents == 0){
                continue;
            }
            Conn* conn = fd2conn[pfd.fd];
            if(pfd.revents & POLLIN){
                assert(conn->want_read);
                handle_read(conn);
            }
            if(pfd.revents & POLLOUT){
                assert(conn->want_write);
                handle_write(conn);
            }
            if( (pfd.revents & POLLERR) or conn->want_close){
                (void)close(pfd.fd);
                fd2conn[pfd.fd] = NULL;
                delete conn;
            }
        }
    }
    return 0;
}